### ISSUE TITLE
Return ResponseEntity<AnnouncementDTO> not ResponseEntity<Void>

### ISSUE THREAD

**Issue by ipaunov** [Morar23/shop#13]
https://github.com/Morar23/shop/blob/5a6fe47248b3665a1709c28ac9ae0a9e8fb7b847/src/main/java/com/morar/shopfinal/controller/AnnouncementController.java#L48

**Comment by Parovsky** [comment]
This method handles a POST request. Why does it need to return something instead of just a status value?

**Comment by ipaunov** [comment]
Returning the new object fits with the REST principle of "Uniform Interface - Manipulation of resources through representations." The complete object is the representation of the new state of the object that was created.

**Comment by Parovsky** [comment]
Thank you for your explanation
