### ISSUE TITLE
How do you delete all with Id. The Id should be unique so there should only be one record with this id. So this is useless, too. Because you can just use deleteById

### ISSUE THREAD

**Issue by ipaunov** [Morar23/shop#35]
https://github.com/Morar23/shop/blob/5a6fe47248b3665a1709c28ac9ae0a9e8fb7b847/src/main/java/com/morar/shopfinal/repository/AnnouncementRepository.java#L14

**Comment by Parovsky** [comment]
when there is no one object with the provided id, deleteById method throws an unchecked exception and deleteAllById just return 0

**Comment by Parovsky** [comment]
org.springframework.dao.EmptyResultDataAccessException: No class com.morar.shopfinal.entity.Announcement entity with id 1 exists!
